# Generated by Django 3.2.10 on 2022-01-02 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('authID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('authName', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'Auth',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('buildingID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('buildingNumber', models.CharField(max_length=10, unique=True)),
                ('buildingName', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'Building',
            },
        ),
        migrations.CreateModel(
            name='DaylyDutyList',
            fields=[
                ('daylyDutyListID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('day', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'Dayly_Duty_List',
            },
        ),
        migrations.CreateModel(
            name='DaylyTotalEvent',
            fields=[
                ('daylyTotalEventID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('day', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'Dayly_Total_Event',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('departmentName', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('deviceID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('deviceNumber', models.CharField(max_length=10, unique=True)),
                ('deviceIP', models.CharField(max_length=20, unique=True)),
                ('deviceState', models.CharField(default='未連線', max_length=10)),
                ('deviceEnable', models.BooleanField()),
                ('deviceCoordinate', models.CharField(max_length=50)),
                ('devicePhoto', models.ImageField(blank=True, null=True, upload_to='')),
                ('deviceNote', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'Device',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('eventNumber', models.CharField(max_length=15, unique=True)),
                ('eventState', models.CharField(default='未處理', max_length=10)),
                ('eventTime', models.DateTimeField(auto_now_add=True)),
                ('eventVideo', models.FileField(blank=True, null=True, upload_to='')),
                ('eventCloseDate', models.DateTimeField(null=True)),
                ('wrongReport', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Event',
            },
        ),
        migrations.CreateModel(
            name='Identify',
            fields=[
                ('identifyID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('identifyName', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'Identify',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('levelID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('levelNumber', models.IntegerField(unique=True)),
                ('numberOfPeople', models.IntegerField()),
            ],
            options={
                'db_table': 'Level',
            },
        ),
        migrations.CreateModel(
            name='YearlyDutyList',
            fields=[
                ('yearlyDutyListID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('year', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'Yearly_Duty_List',
            },
        ),
        migrations.CreateModel(
            name='YearlyTotalEvent',
            fields=[
                ('yearlyTotalEventID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('year', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'Yearly_Total_Event',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('JID', models.CharField(max_length=15, unique=True)),
                ('userName', models.CharField(max_length=10)),
                ('gentle', models.CharField(max_length=2)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('gmail', models.EmailField(max_length=50, unique=True)),
                ('accountName', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('accountEnable', models.BooleanField(max_length=1)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.auth', to_field='authName')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department', to_field='departmentName')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('RoomID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('roomNumber', models.CharField(max_length=10, unique=True)),
                ('floor', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.building', to_field='buildingName')),
            ],
            options={
                'db_table': 'Room',
            },
        ),
        migrations.CreateModel(
            name='MonthlyTotalEvent',
            fields=[
                ('monthlyTotalEventID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('month', models.IntegerField(unique=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.yearlytotalevent', to_field='year')),
            ],
            options={
                'db_table': 'Monthly_Total_Event',
            },
        ),
        migrations.CreateModel(
            name='MonthlyDutyList',
            fields=[
                ('monthlyDutyListID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('month', models.IntegerField(unique=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.yearlydutylist', to_field='year')),
            ],
            options={
                'db_table': 'Monthly_Duty_List',
            },
        ),
        migrations.CreateModel(
            name='EventPIC',
            fields=[
                ('eventPICID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('PIC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.event', to_field='eventNumber')),
            ],
            options={
                'db_table': 'Event_PIC',
            },
        ),
        migrations.CreateModel(
            name='EventName',
            fields=[
                ('eventNameID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('eventName', models.CharField(max_length=10, unique=True)),
                ('identify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.identify', to_field='identifyName')),
            ],
            options={
                'db_table': 'Event_Name',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='PIC',
            field=models.ManyToManyField(through='myapp.EventPIC', to='myapp.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.daylytotalevent', to_field='day'),
        ),
        migrations.AddField(
            model_name='event',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.device', to_field='deviceNumber'),
        ),
        migrations.AddField(
            model_name='event',
            name='eventName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.eventname', to_field='eventName'),
        ),
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.level', to_field='levelNumber'),
        ),
        migrations.CreateModel(
            name='DutyList',
            fields=[
                ('dutyListID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('workTimeStart', models.TimeField()),
                ('workTimeEnd', models.TimeField()),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.building', to_field='buildingName')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.daylydutylist', to_field='day')),
                ('dealWithEvent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.event', to_field='eventNumber')),
            ],
            options={
                'db_table': 'Duty_List',
            },
        ),
        migrations.CreateModel(
            name='DeviceFeature',
            fields=[
                ('deviceFeatureID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('deviceFeatureEnable', models.BooleanField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.device', to_field='deviceNumber')),
                ('identify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.identify', to_field='identifyName')),
            ],
            options={
                'db_table': 'Device_Feature',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='identify',
            field=models.ManyToManyField(through='myapp.DeviceFeature', to='myapp.Identify'),
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.room', to_field='roomNumber'),
        ),
        migrations.AddField(
            model_name='daylytotalevent',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.monthlytotalevent', to_field='month'),
        ),
        migrations.AddField(
            model_name='daylydutylist',
            name='UID',
            field=models.ManyToManyField(through='myapp.DutyList', to='myapp.User'),
        ),
        migrations.AddField(
            model_name='daylydutylist',
            name='building',
            field=models.ManyToManyField(through='myapp.DutyList', to='myapp.Building'),
        ),
        migrations.AddField(
            model_name='daylydutylist',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.monthlydutylist', to_field='month'),
        ),
    ]
