# Generated by Django 3.2.10 on 2021-12-30 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('authID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('authName', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'Auth',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('buildingID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('buildingNumber', models.CharField(max_length=10, unique=True)),
                ('buildingName', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'Building',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('departmentName', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('deviceID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('deviceNumber', models.CharField(max_length=10, unique=True)),
                ('deviceIP', models.CharField(max_length=20, unique=True)),
                ('deviceState', models.CharField(max_length=10)),
                ('deviceEnable', models.BooleanField()),
                ('deviceCoordinate', models.CharField(max_length=50)),
                ('devicePhoto', models.ImageField(upload_to='')),
                ('deviceNote', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Device',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('eventNumber', models.CharField(max_length=15, unique=True)),
                ('eventState', models.CharField(max_length=10)),
                ('eventTime', models.DateTimeField(auto_now_add=True)),
                ('eventVideo', models.FileField(upload_to='')),
                ('eventCloseDate', models.DateTimeField(blank=True, default=None)),
            ],
            options={
                'db_table': 'Event',
            },
        ),
        migrations.CreateModel(
            name='Identify',
            fields=[
                ('identifyID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('identifyName', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'Identify',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('levelID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('levelNumber', models.IntegerField(unique=True)),
                ('numberOfPeople', models.IntegerField()),
            ],
            options={
                'db_table': 'Level',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('JID', models.CharField(max_length=15, unique=True)),
                ('userName', models.CharField(max_length=10)),
                ('gentle', models.CharField(max_length=2)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('gmail', models.EmailField(max_length=50, unique=True)),
                ('accountName', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('accountEnable', models.BooleanField(max_length=1)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.auth')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('RoomID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('roomNumber', models.CharField(max_length=10)),
                ('floor', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.building')),
            ],
            options={
                'db_table': 'Room',
            },
        ),
        migrations.CreateModel(
            name='EventPIC',
            fields=[
                ('EventPICID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('PIC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.event')),
            ],
            options={
                'db_table': 'EventPIC',
            },
        ),
        migrations.CreateModel(
            name='EventName',
            fields=[
                ('eventNameID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('eventName', models.CharField(max_length=10, unique=True)),
                ('identify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.identify')),
            ],
            options={
                'db_table': 'EventName',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='PIC',
            field=models.ManyToManyField(through='myapp.EventPIC', to='myapp.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.device'),
        ),
        migrations.AddField(
            model_name='event',
            name='eventName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.eventname'),
        ),
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.level'),
        ),
        migrations.CreateModel(
            name='DeviceFeature',
            fields=[
                ('deviceFeatureID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('deviceFeatureEnable', models.BooleanField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.device')),
                ('identify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.identify')),
            ],
            options={
                'db_table': 'DeviceFeature',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='identify',
            field=models.ManyToManyField(through='myapp.DeviceFeature', to='myapp.Identify'),
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.room'),
        ),
    ]
