# Generated by Django 3.2.10 on 2022-01-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceIP',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
