# Generated by Django 3.2.10 on 2021-12-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='devicefeature',
            table='Device_Feature',
        ),
        migrations.AlterModelTable(
            name='eventname',
            table='Event_Name',
        ),
        migrations.AlterModelTable(
            name='eventpic',
            table='Event_PIC',
        ),
    ]
