# Generated by Django 3.2.10 on 2022-01-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_device_deviceip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceCoordinate',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
