# Generated by Django 3.2.10 on 2022-01-01 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220101_1114'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='daylytotalevent',
            table='Dayly_Total_Event',
        ),
        migrations.AlterModelTable(
            name='monthlytotalevent',
            table='Monthly_Total_Event',
        ),
        migrations.AlterModelTable(
            name='yearlytotalevent',
            table='Yearly_Total_Event',
        ),
    ]
